name: Release Base Components
on: workflow_dispatch
jobs:
  release:
    name: Release and publish module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build:production
      - name: Run tests and do code coverage check
        run: npm run test:coverage
      - name: Release module and publish it in github.com and npmjs.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
        run: npm run semantic-release
